2021-01-20 16:04:58.920304: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\服务器版本2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-20 16:04:58.920304: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-20 16:04:58.935997: wfastcgi.py 3.0.0 initialized
2021-01-20 16:05:11.995701: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-20 16:05:11.996732: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-20 16:05:11.997787: wfastcgi.py 3.0.0 initialized
2021-01-20 16:08:25.031546: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-20 16:08:25.830657: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-20 16:08:25.892161: wfastcgi.py 3.0.0 initialized
2021-01-20 16:08:42.971773: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-20 16:08:42.972798: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-20 16:08:42.974373: wfastcgi.py 3.0.0 initialized
2021-01-20 16:08:49.843353: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-20 16:08:49.843353: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-20 16:08:49.843353: wfastcgi.py 3.0.0 initialized
2021-01-20 16:13:42.011660: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-01-20 16:13:42.011660: Running on_exit tasks
2021-01-20 16:13:42.011660: wfastcgi.py 3.0.0 closed
2021-01-20 16:33:03.828183: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-20 16:33:03.890750: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-20 16:33:04.869377: wfastcgi.py 3.0.0 initialized
2021-01-20 16:40:23.835064: wfastcgi.py exiting because simpleui_test\settings.py has changed, matching .*((\.py)|(\.config))$
2021-01-20 16:40:23.836102: Running on_exit tasks
2021-01-20 16:40:54.922174: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-20 16:40:54.922174: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-20 16:40:54.922174: wfastcgi.py 3.0.0 initialized
2021-01-20 16:46:38.829607: wfastcgi.py exiting because simpleui_test\urls.py has changed, matching .*((\.py)|(\.config))$
2021-01-20 16:46:38.831658: Running on_exit tasks
2021-01-20 16:50:45.959412: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-20 16:50:45.959412: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-20 16:50:45.960446: wfastcgi.py 3.0.0 initialized
2021-01-20 16:55:47.024690: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-20 16:55:47.025709: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-20 16:55:47.027680: wfastcgi.py 3.0.0 initialized
2021-01-20 17:20:56.962133: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-20 17:20:56.963158: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-20 17:20:56.963158: wfastcgi.py 3.0.0 initialized
2021-01-20 17:34:24.874921: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-20 17:34:24.874921: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-20 17:34:24.875947: wfastcgi.py 3.0.0 initialized
2021-01-20 17:40:02.826870: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-01-20 17:40:02.826870: Running on_exit tasks
2021-01-20 17:40:02.826870: wfastcgi.py 3.0.0 closed
2021-01-20 18:42:35.909973: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-20 18:42:35.909973: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-20 18:42:35.909973: wfastcgi.py 3.0.0 initialized
2021-01-20 18:47:48.985782: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-01-20 18:47:48.985782: Running on_exit tasks
2021-01-20 18:47:48.985782: wfastcgi.py 3.0.0 closed
2021-01-20 18:48:29.682313: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-20 18:48:29.682313: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-20 18:48:29.682313: wfastcgi.py 3.0.0 initialized
2021-01-20 18:55:47.376416: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-20 18:55:47.376416: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-20 18:55:47.392088: wfastcgi.py 3.0.0 initialized
2021-01-20 18:55:48.582737: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-20 18:55:48.582737: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-20 18:55:48.582737: wfastcgi.py 3.0.0 initialized
2021-01-20 19:22:09.735048: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-20 19:22:09.735048: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-20 19:22:09.735048: wfastcgi.py 3.0.0 initialized
2021-01-20 19:22:15.274904: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-20 19:22:15.274904: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-20 19:22:15.274904: wfastcgi.py 3.0.0 initialized
2021-01-20 21:19:32.186263: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-20 21:19:32.201950: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-20 21:19:32.201950: wfastcgi.py 3.0.0 initialized
2021-01-21 00:26:31.023451: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-21 00:26:31.023451: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-21 00:26:31.023451: wfastcgi.py 3.0.0 initialized
2021-01-21 00:26:40.208767: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-21 00:26:40.208767: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-21 00:26:40.208767: wfastcgi.py 3.0.0 initialized
2021-01-21 00:59:20.771350: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-21 00:59:20.771350: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-21 00:59:20.771350: wfastcgi.py 3.0.0 initialized
2021-01-21 02:12:07.602424: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-21 02:12:07.602424: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-21 02:12:07.602424: wfastcgi.py 3.0.0 initialized
2021-01-21 05:17:31.014718: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-21 05:17:31.014718: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-21 05:17:31.014718: wfastcgi.py 3.0.0 initialized
2021-01-21 10:45:25.900587: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-21 10:45:25.900587: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-21 10:45:25.900587: wfastcgi.py 3.0.0 initialized
2021-01-21 10:45:34.992736: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-21 10:45:34.992736: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-21 10:45:35.008908: wfastcgi.py 3.0.0 initialized
2021-01-21 11:45:22.199642: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-21 11:45:22.199642: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-21 11:45:22.199642: wfastcgi.py 3.0.0 initialized
2021-01-21 12:32:45.845292: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-21 12:32:45.845292: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-21 12:32:45.845292: wfastcgi.py 3.0.0 initialized
2021-01-21 15:25:07.061265: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-21 15:25:07.061265: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-21 15:25:07.061265: wfastcgi.py 3.0.0 initialized
2021-01-21 16:42:22.274512: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-21 16:42:22.274512: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-21 16:42:22.274512: wfastcgi.py 3.0.0 initialized
2021-01-21 17:03:09.281193: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-21 17:03:09.282220: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-21 17:03:09.283255: wfastcgi.py 3.0.0 initialized
2021-01-21 17:04:42.092115: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-21 17:04:42.092115: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-21 17:04:42.116799: wfastcgi.py 3.0.0 initialized
2021-01-21 17:04:42.151548: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-21 17:04:42.152571: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-21 17:04:42.153799: wfastcgi.py 3.0.0 initialized
2021-01-21 22:09:24.686519: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-21 22:09:24.686519: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-21 22:09:24.686519: wfastcgi.py 3.0.0 initialized
2021-01-21 22:47:53.271402: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-21 22:47:53.271402: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-21 22:47:53.287121: wfastcgi.py 3.0.0 initialized
2021-01-22 02:22:04.043931: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-22 02:22:04.043931: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-22 02:22:04.043931: wfastcgi.py 3.0.0 initialized
2021-01-22 06:27:32.195396: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-22 06:27:32.195396: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-22 06:27:32.195396: wfastcgi.py 3.0.0 initialized
2021-01-22 07:43:45.557011: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-22 07:43:45.557011: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-22 07:43:45.557011: wfastcgi.py 3.0.0 initialized
2021-01-22 07:51:53.587430: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-01-22 07:51:53.587430: Running on_exit tasks
2021-01-22 08:19:33.726310: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-22 08:19:33.726310: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-22 08:19:33.726310: wfastcgi.py 3.0.0 initialized
2021-01-22 08:53:28.247467: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-22 08:53:28.247467: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-22 08:53:28.247467: wfastcgi.py 3.0.0 initialized
2021-01-22 12:26:50.624298: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-22 12:26:50.624298: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-22 12:26:50.624298: wfastcgi.py 3.0.0 initialized
2021-01-22 12:26:53.363388: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-22 12:26:53.363388: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-22 12:26:53.379132: wfastcgi.py 3.0.0 initialized
2021-01-22 12:26:53.379132: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-01-22 12:26:53.379132: wfastcgi.py will restart when files in C:\inetpub\wwwroot\zhihao2021.1.5\ are changed: .*((\.py)|(\.config))$
2021-01-22 12:26:53.394832: wfastcgi.py 3.0.0 initialized
2021-01-22 12:32:06.164056: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\zhihao2021.1.5\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
